#!/usr/bin/env ruby

# Daemons sets pwd to /, so we have to explicitly set Rails.root
Rails.root = File.expand_path(File.join(File.dirname(__FILE__), '..'))

require 'rubygems'
require 'apn'
require 'apn/sender_daemon'

APN::SenderDaemon.new(ARGV).daemonize